name: WannaBe-Test-Build

on:
  push:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest
    outputs:
      report-path: ${{ steps.upload.outputs.report-path }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Make Directory for results
        run: mkdir -p testResults

      - name: Run POSTMAN collection
        run: |
          newman run petstore.collection.json \
            -r htmlextra \
            --reporter-htmlextra-export testResults/htmlreport.html \
            --reporter-htmlextra-darkTheme

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: testResults/htmlreport.html

  deploy-report:
    needs: test-api
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: html-report
          path: public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
